
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class AdminDeleteFrm extends javax.swing.JFrame {

    /**
     * Creates new form DeleteFrm
     */
    public AdminDeleteFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblParent = new javax.swing.JTable();
        btnReload = new javax.swing.JButton();
        btnSDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTeacher = new javax.swing.JTable();
        btnTDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        edtName = new java.awt.TextField();
        edtSname = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete");
        setPreferredSize(new java.awt.Dimension(777, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Delete");

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Surname", "Date of Birth", "Gender", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        tblParent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Surname", "Contact Number", "Address", "Children Enrolled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblParent);

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnSDelete.setText("Delete Selected Student");
        btnSDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnPDelete.setText("Delete Selected Parent");
        btnPDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDeleteActionPerformed(evt);
            }
        });

        tblTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Surname", "Grade"
            }
        ));
        jScrollPane3.setViewportView(tblTeacher);

        btnTDelete.setText("Delete Selected Teacher");
        btnTDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        label1.setText("Name:");

        label2.setText("Surname:");

        edtName.setColumns(10);

        edtSname.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSDelete)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPDelete)
                    .addComponent(btnReload))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTDelete)
                    .addComponent(btnBack))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Main pro = new Main();
            pro.createConnection();
            
            Statement Sstmt = (Statement) Main.con.createStatement();
            String Ssql = "SELECT * FROM tblstudent";
            ResultSet Srs = Sstmt.executeQuery(Ssql);

            Srs.beforeFirst();
            DefaultTableModel Stm = (DefaultTableModel)tblStudent.getModel();
            Stm.setRowCount(0);

            while (Srs.next()) {
                String id = Integer.toString(Srs.getInt("StudentID"));
                String name = Srs.getString("Name");
                String sname = Srs.getString("Surname");
                String dob = (Srs.getDate("DateOfBirth")).toString();
                String gender = Srs.getString("Gender");
                String grade = Integer.toString(Srs.getInt("Grade"));
                
                String[] data = {id, name, sname, dob, gender, grade};
                
                Stm.addRow(data);
            }
            
            Statement Pstmt = (Statement) Main.con.createStatement();
            String Psql = "SELECT * FROM tblparent";
            ResultSet Prs = Pstmt.executeQuery(Psql);

            Prs.beforeFirst();
            DefaultTableModel Ptm = (DefaultTableModel)tblParent.getModel();
            Ptm.setRowCount(0);

            while (Prs.next()) {
                String id = Integer.toString(Prs.getInt("ParentID"));
                String name = Prs.getString("Name");
                String sname = Prs.getString("Surname");
                String contact = Prs.getString("ContactNumber");
                String address = Prs.getString("Address");
                String enrolled = Integer.toString(Prs.getInt("NumberEnrolled"));
                
                String[] data = {id, name, sname, contact, address, enrolled};
                
                Ptm.addRow(data);
            }
            
            Statement Tstmt = (Statement) Main.con.createStatement();
            String Tsql = "SELECT * FROM tblteacher";
            ResultSet Trs = Tstmt.executeQuery(Tsql);

            Trs.beforeFirst();
            DefaultTableModel Ttm = (DefaultTableModel)tblTeacher.getModel();
            Ttm.setRowCount(0);

            while (Trs.next()) {
                String id = Integer.toString(Trs.getInt("TeacherID"));
                String name = Trs.getString("Name");
                String sname = Trs.getString("Surname");
                String grade = Integer.toString(Trs.getInt("Grade"));
                
                String[] data = {id, name, sname, grade};
                
                Ttm.addRow(data);
            }
            
            Main.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminDeleteFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        try {
            Main pro = new Main();
            pro.createConnection();
            
            Statement Sstmt = (Statement) Main.con.createStatement();
            String Ssql = "SELECT * FROM tblstudent";
            ResultSet Srs = Sstmt.executeQuery(Ssql);

            Srs.beforeFirst();
            DefaultTableModel Stm = (DefaultTableModel)tblStudent.getModel();
            Stm.setRowCount(0);

            while (Srs.next()) {
                String id = Integer.toString(Srs.getInt("StudentID"));
                String name = Srs.getString("Name");
                String sname = Srs.getString("Surname");
                String dob = (Srs.getDate("DateOfBirth")).toString();
                String gender = Srs.getString("Gender");
                String grade = Integer.toString(Srs.getInt("Grade"));
                
                String[] data = {id, name, sname, dob, gender, grade};
                
                Stm.addRow(data);
            }
            
            Statement Pstmt = (Statement) Main.con.createStatement();
            String Psql = "SELECT * FROM tblparent";
            ResultSet Prs = Pstmt.executeQuery(Psql);

            Prs.beforeFirst();
            DefaultTableModel Ptm = (DefaultTableModel)tblParent.getModel();
            Ptm.setRowCount(0);

            while (Prs.next()) {
                String id = Integer.toString(Prs.getInt("ParentID"));
                String name = Prs.getString("Name");
                String sname = Prs.getString("Surname");
                String contact = Prs.getString("ContactNumber");
                String address = Prs.getString("Address");
                String enrolled = Integer.toString(Prs.getInt("NumberEnrolled"));
                
                String[] data = {id, name, sname, contact, address, enrolled};
                
                Ptm.addRow(data);
            }
            
            Statement Tstmt = (Statement) Main.con.createStatement();
            String Tsql = "SELECT * FROM tblstudent";
            ResultSet Trs = Sstmt.executeQuery(Tsql);

            Trs.beforeFirst();
            DefaultTableModel Ttm = (DefaultTableModel)tblTeacher.getModel();
            Stm.setRowCount(0);

            while (Srs.next()) {
                String id = Integer.toString(Srs.getInt("TeacherID"));
                String name = Srs.getString("Name");
                String sname = Srs.getString("Surname");
                String grade = Integer.toString(Srs.getInt("Grade"));
                
                String[] data = {id, name, sname, grade};
                
                Ttm.addRow(data);
            }
            
            Main.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminDeleteFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnSDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSDeleteActionPerformed
        try {                
            int row = tblStudent.getSelectedRow();
            DefaultTableModel model= (DefaultTableModel)tblStudent.getModel();            
            int id = Integer.parseInt(model.getValueAt(row, 0).toString());
            
            int input = JOptionPane.showConfirmDialog(null,
                "You are about to delete the selected student", "Warning",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
            if (input == 0){
                Main pro = new Main();
                pro.createConnection();
                
                String sql = "DELETE FROM tblstudent WHERE StudentID = ?";
                PreparedStatement pstmt = Main.con.prepareStatement(sql);
                pstmt.setInt(1, id);
                pstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Student deleted");
                
                Main.con.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Student " + e);
        }
    }//GEN-LAST:event_btnSDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            new AdminDashboard().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDeleteActionPerformed
        try {
            int row = tblParent.getSelectedRow();
            DefaultTableModel model= (DefaultTableModel)tblParent.getModel();            
            String id = (model.getValueAt(row, 0).toString());
            
            int input = JOptionPane.showConfirmDialog(null,
                "You are about to delete the selected parent", "Warning",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
            if (input == 0){
                Main pro = new Main();
                pro.createConnection();
                
                
                String sql = "DELETE FROM tblparent WHERE ParentID = ?";
                PreparedStatement pstmt = Main.con.prepareStatement(sql);
                pstmt.setString(1, id);
                pstmt.executeUpdate();
                pstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Parent deleted");
                
                Main.con.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Parent " + e);
        }
    }//GEN-LAST:event_btnPDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String fname = "";
        String fsname = "";
        
        if (!edtName.getText().equals("")){
            fname = edtName.getText();
        }
        
        if (!edtSname.getText().equals("")){
            fsname = edtSname.getText();
        }
        
        try {
            Main pro = new Main();
            pro.createConnection();
            
            Statement Sstmt = (Statement) Main.con.createStatement();
            String Ssql = "SELECT * FROM tblstudent WHERE (Name LIKE '%"+fname+"%' AND Surname LIKE '%"+fsname+"%')";
            ResultSet Srs = Sstmt.executeQuery(Ssql);

            Srs.beforeFirst();
            DefaultTableModel Stm = (DefaultTableModel)tblStudent.getModel();
            Stm.setRowCount(0);

            while (Srs.next()) {
                String id = Integer.toString(Srs.getInt("StudentID"));
                String name = Srs.getString("Name");
                String sname = Srs.getString("Surname");
                String dob = (Srs.getDate("DateOfBirth")).toString();
                String gender = Srs.getString("Gender");
                String grade = Integer.toString(Srs.getInt("Grade"));
                
                String[] data = {id, name, sname, dob, gender, grade};
                
                Stm.addRow(data);
            }
            
            Statement Pstmt = (Statement) Main.con.createStatement();
            String Psql = "SELECT * FROM tblparent WHERE (Name LIKE '%"+fname+"%' AND Surname LIKE '%"+fsname+"%')";
            ResultSet Prs = Pstmt.executeQuery(Psql);

            Prs.beforeFirst();
            DefaultTableModel Ptm = (DefaultTableModel)tblParent.getModel();
            Ptm.setRowCount(0);

            while (Prs.next()) {
                String id = Integer.toString(Prs.getInt("ParentID"));
                String name = Prs.getString("Name");
                String sname = Prs.getString("Surname");
                String contact = Prs.getString("ContactNumber");
                String address = Prs.getString("Address");
                String enrolled = Integer.toString(Prs.getInt("NumberEnrolled"));
                
                String[] data = {id, name, sname, contact, address, enrolled};
                
                Ptm.addRow(data);
            }
            
            Statement Tstmt = (Statement) Main.con.createStatement();
            String Tsql = "SELECT * FROM tblstudent WHERE (Name LIKE '%"+fname+"%' AND Surname LIKE '%"+fsname+"%')";
            ResultSet Trs = Sstmt.executeQuery(Tsql);

            Trs.beforeFirst();
            DefaultTableModel Ttm = (DefaultTableModel)tblTeacher.getModel();
            Stm.setRowCount(0);

            while (Trs.next()) {
                String id = Integer.toString(Trs.getInt("TeacherID"));
                String name = Trs.getString("Name");
                String sname = Trs.getString("Surname");
                String grade = Integer.toString(Trs.getInt("Grade"));
                
                String[] data = {id, name, sname, grade};
                
                Stm.addRow(data);
            }
            
            Main.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnTDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDeleteActionPerformed
        try {                
            int row = tblTeacher.getSelectedRow();
            DefaultTableModel model= (DefaultTableModel)tblTeacher.getModel();            
            int id = Integer.parseInt(model.getValueAt(row, 0).toString());
            
            int input = JOptionPane.showConfirmDialog(null,
                "You are about to delete the selected Teacher", "Warning",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
            if (input == 0){
                Main pro = new Main();
                pro.createConnection();
                
                String sql = "DELETE FROM tblteacher WHERE TeacherID = ?";
                PreparedStatement pstmt = Main.con.prepareStatement(sql);
                pstmt.setInt(1, id);
                pstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Teacher deleted");
                
                Main.con.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Teacher " + e);
        }
    }//GEN-LAST:event_btnTDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDeleteFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPDelete;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTDelete;
    private java.awt.TextField edtName;
    private java.awt.TextField edtSname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTable tblParent;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTable tblTeacher;
    // End of variables declaration//GEN-END:variables
}
